### ISSUE TITLE
Scikit learn estimator optimization

### ISSUE THREAD

**Issue by aminevsaziz** [Hvass-Labs/swarmops#1]
Is there a possibility to fine tune Scikit estimator let's say RandomForest using swarmops?

**Comment by Hvass-Labs** [comment]
That is probably possible but you would have to write all the connecting code yourself.

It is probably much easier to use scikit-optimize which was specifically developed for that purpose:

https://github.com/scikit-optimize/scikit-optimize

https://scikit-optimize.github.io/notebooks/sklearn-gridsearchcv-replacement.html

**Comment by aminevsaziz** [comment]
@Hvass-Labs  so there's no possibility to even use particle swarm optimization in for hyperparameters tunning in python?
